### ISSUE TITLE
Multiple concurrent requests

### ISSUE THREAD

**Issue by leon0707** [clemfromspace/scrapy-selenium#13]
This middleware uses only one webdriver. If you have multiple requests running concurrently, probably you cannot get the correct result.

@clemfromspace please correct me if i'm wrong.

**Comment by clemfromspace** [comment]
I guess you are right in the way of all the calls to the driver are synchronous.
The spider will handle the requests in a non-concurrently way (related to #2 ?)
One solution should be to remplace selenium with an asynchrone alternative, like https://github.com/HDE/arsenic or https://miyakogi.github.io/pyppeteer/

I am currently thinking about implementing a similar middleware using puppeteer, you can see some code here: https://gist.github.com/clemfromspace/bbe9a99da1e86a753baa00e394234b8c (not tested at all, no guarantee it will work)

**Comment by leon0707** [comment]
I found the problem when the scrapy engine sent multiple SeleniumRequests to downloader middleware. In the spider callback function, response.meta['driver'].url is not the same as response.url.

I actually stick with selenium. I generate a webdriver for each request, and it will quit in the spider callback function. The only problem which bothers me is that multiple webdrivers are created, and they consume a lot of memory and can stay long time before being processed. However, it can be solved by setting a positive priority in the request.

**Comment by ypawar159** [comment]
I found this issue when trying to create a new one for concurrent requests feature.
I did look at async approach using pyppeteer mentioned in the link. And I don't think it solves the multiple requests simultaneously.
What I think of is every spider has max concurrent connection settings, then can we use it to start new driver with max being that value. And a queue mechanism to distribute the load for each request?

**Comment by joaovictor42** [comment]
I still have a question about this issue. I'm developing a project where I necessarily need to use Scrapy with Selenium, due to some of its features. But my main bottleneck is concurrence. To get around this problem, I thought of distributing in the same spider part of the requests for Scrapy-Selenium with a single browser and another part for Scrapy-Splash, which allows concurrent requests using the CONCURRENT_REQUESTS setting. In this context where I have two concurrent middlewares, can I trust that the results returned by Scrapy-Selenium are consistent?

@clemfromspace  could you help me with the question?
